version: "2.3"

services:
  product_service:
    image: product_service
    build:
      context: .
      dockerfile: ./Distributed_Systems_Lab_1/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ".:/product_service"
    environment:
      HIGH_LIMIT: 5
      LOW_LIMIT: 20
      TIMEOUT: 1s
      GATEWAY_ADDR: https://httpbin.org/post
      IP: 0.0.0.0
      PORT: 8080
      MongoDbURI: mongodb+srv://admin:admin@cluster0.cnciz.mongodb.net/products_service?retryWrites=true&w=majority
